{{ if .Values.regularMoves.monthly.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{- .Release.Name }}-mmv
  labels:
    {{- include "job-backup-db.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: {{ .Values.cron.concurrencyPolicy }}
  schedule: "{{ .Values.regularMoves.monthly.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.cron.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cron.failedJobsHistoryLimit }}
  suspend: {{ .Values.cron.suspend }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cron.backoffLimit }}
      template:
        metadata:
          labels:
            {{- include "job-backup-db.labels" . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          restartPolicy: {{ .Values.restartPolicy }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.serviceAccountName }}
          serviceAccountName: {{ . }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
          - name: {{ .Chart.Name }}
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            args:
              - mv
              - {{ include "job-backup-db.weeklyPath" . }}
              - {{ include "job-backup-db.monthlyPath" . }}
            {{- with .Values.envFrom }}
            envFrom:
              {{- toYaml . | nindent 12 }}
            {{- end }}
            env:
            - name: BAGCLI_RETENTION_TIME
              value: "{{ .Values.regularMoves.monthly.retentionTime }}"
            {{- if .Values.regularMoves.monthly.webhookUrl }}
            - name: BAGCLI_WEBHOOK_URL
              value: {{ .Values.regularMoves.monthly.webhookUrl }}
            {{- end }}
            {{- if .Values.regularMoves.monthly.heartbeatUrl }}
            - name: BAGCLI_HEARTBEAT_URL
              value: {{ .Values.regularMoves.monthly.heartbeatUrl }}
            {{- end }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end -}}
            {{- with .Values.resources -}}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            volumeMounts:
            - mountPath: /home/job/.config/rclone
              name: rclone
            {{- if .Values.ephemeralVolume.enabled }}
            - mountPath: {{ .Values.ephemeralVolume.mountPath }}
              name: {{ .Values.ephemeralVolume.name }}
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumes:
          - name: rclone
            secret:
              secretName: {{ .Values.backup.rclone.secret.name }}
              items:
              - key: {{ .Values.backup.rclone.secret.key }}
                path: rclone.conf
          {{- with .Values.volumes }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
{{- end -}}