#!/usr/bin/env sh

set -e
. "$BAGCLI_WORKDIR/common"

cli_help_deploy() {
  echo "
Command: mariadb
Usage: 
  mariadb <database_name>"
  exit 1
}

[ ! -n "$1" ] && cli_help_deploy

export MARIADB_DATABASE=$1
export MARIADB_HOST=$BAGCLI_DATABASE_HOST
export MARIADB_USER=$BAGCLI_DATABASE_USER
export MARIADB_TCP_PORT=$BAGCLI_DATABASE_PORT
export MARIADB_PWD=$BAGCLI_DATABASE_PASS

cli_log "Backup database $MARIADB_DATABASE with user $MARIADB_USER BEGIN"

cli_log "ENV variables"
env | grep "BAGCLI_*" | grep -v "PASS"

cli_log "Executing mysqldump"

mysqldump \
  --default-character-set=utf8mb4 \
  --host $MARIADB_HOST \
  --user $MARIADB_USER \
  --port $MARIADB_TCP_PORT \
  -p"$MARIADB_PWD" \
  --single-transaction \
  $MARIADB_DATABASE | gzip -9 -c > /tmp/backup.sql.gz

cli_log "Removing backups older than $BAGCLI_RETENTION_TIME"
mc rm --recursive --force --older-than $BAGCLI_RETENTION_TIME s3/$BAGCLI_BUCKET_PATH/${MARIADB_DATABASE}_*.sql.gz || true

cli_log "Copy of local dump to s3"
mc cp --quiet /tmp/backup.sql.gz s3/$BAGCLI_BUCKET_PATH/${MARIADB_DATABASE}_$(date +'%d_%m_%Y__%H_%M_%S').sql.gz

cli_log "Cleaning /tmp folder"
rm /tmp/backup.sql.gz

cli_log "Job completed !"
