#!/usr/bin/env sh

cli_log() {
  script_name=${0##*/}
  timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  echo "== $script_name $timestamp $1"
}

heartbeatPing() {
  if [ -z "$BAGCLI_HEARTBEAT_URL" ]; then
    return
  fi
  curl -v -XGET $BAGCLI_HEARTBEAT_URL
}

postToWebhook(){
  if [ -z "$BAGCLI_WEBHOOK_URL" ] && [ -z "$BAGCLI_WEBHOOK_CHANNEL" ]; then
    return
  fi
  curl -v -X POST --data-urlencode "payload={\"channel\": \"$BAGCLI_WEBHOOK_CHANNEL\", \"username\": \"cronjob_backup_sql\", \"text\": \"cronjob succeed.\", \"icon_emoji\": \":gear:\"}" $BAGCLI_WEBHOOK_URL
}
